name: Push Container to Artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    
    - run: |
        docker build -t ghcr.io/demoserievideo/sample-artifact-docker/sample:latest -f Dockerfile .
        docker push ghcr.io/demoserievideo/sample-artifact-docker/sample:latest
