name: Push Container to Artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - run: |
        docker build -t docker.pkg.github.com/demoserievideo/sample-artifact-docker/sample:latest -f Dockerfile .
        ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u ${{ secrets.GH_PACKAGES_USER }}  --password-stdin
        docker push docker.pkg.github.com/demoserievideo/sample-artifact-docker/sample:latest
