name: Push Container to Artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    
    - run: ls
    
    - run: docker build -t counter-image -f Dockerfile .

    - run: |
        docker build -t docker.pkg.github.com/demoserievideo/sample-artifact-docker:latest -f Dockerfile .
        docker push docker.pkg.github.com/demoserievideo/sample-artifact-docker:latest
